Auction layout fixes & various UI/UX tweaks
cadenforrest/DotaLeagueSite pull request #128
Opened 2023-08-10 18:41 UTC by l-ohman

This branch addresses various small issues with the auction layout, the main ones being the containers that would change in size when their children re-rendered (such as the AuctionStatus or the DataGridSelection). There was also a large improvement to the "Nomination" process; now it's clearer when it's your turn to nominate, and the process to do so is somewhat less confusing.

_*This may need some tweaks/adjustments once the other currently open PRs have been merged._

---

## More consistent header between draft states

![header—nomination stage](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/7fea4151-7684-4c89-8162-d163ec523594)
![header—bid stage](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/5b7fac49-c1fd-4056-b358-56cc76e041dd)
![header—break](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/f02a79c1-f6c0-4cff-b5d8-aaf96bc88d2d)

## Improved nomination UX
Snackbar changes:
  - Moved from bottom left to top center
  - Added basic instructions for how to nominate
  - Increased default duration to 10s

![nomination snackbar](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/fb380028-0ee7-4e43-bd14-b23a1bdff5f6)

There is now a slight glow around the `SelectedPlayer` component when a user is selecting a player to be nominated. (It is quite subtle in this cropped image, but in the context of the whole page it stands out much better):

![highlighted nomination container](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/ffc3f8f9-b311-44e8-8aea-69244b2430b1)

The "Nominate" button now only shows up on Lots that are available. For Lots that have already been sold, a placeholder button indicates their status:

![attempting to nominate a sold player](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/dd3581de-0af8-4012-8790-adc54a10643a)

2023-08-11 21:48 UTC, cadenforrest requested changes
Looks good, just a ❓ and a nitpick

2023-08-11 21:48 UTC, cadenforrest commented on frontend/components/auction/BidderActions/BidderMenu.tsx
> +
nitpick: let's move this to the top of the file with the other hooks

2023-08-11 21:48 UTC, cadenforrest commented on frontend/common/lib.ts
>  }
🤔 For us less mathematically inclined, this can be pretty hard to stare at... We should add a comment with example inputs/outputs of this function so that people aren't trying to reverse-engineer the math here. Or maybe a chart of medals to MMR?

2023-08-11 21:50 UTC, cadenforrest commented on frontend/components/auction/DetailedPlayerInfo/NominateButton.tsx
> +        </Button>
I had to double-take on the screenshots as to what this means - kind of a nitpick, but it may be more intuitive to say "Player unavailable", or "Player already drafted" or something that starts with "player"

2023-08-11 21:52 UTC, cadenforrest commented on frontend/common/types.ts
> +      lot.custom_lot_attributes.mmr = Math.floor(lot.custom_lot_attributes.mmr);
Why the `Math.floor`?

2023-08-11 21:53 UTC, cadenforrest commented on frontend/common/types.ts
> +        timeNominated: lot.time_nominated ? new Date(lot.time_nominated) : null,
Does JS let you do just `new Date(lot.time_nominated) || null`, or `new Date(lot.time_nominated || null)` instead of the ternary?

2023-08-11 21:56 UTC, cadenforrest commented on frontend/components/auction/BidderActions/BidderMenu.tsx
> +      );
🤔 When will something ever be "too long" and not "more than your balance"?

2023-08-12 00:22 UTC, l-ohman commented on frontend/common/lib.ts
>  }
I have added the link to the Dota 2 wiki that explains the badge/mmr conversion, and I added some comments that explain why certain operations are done. (And for what it's worth, this math could definitely be written cleaner as well.)

2023-08-12 00:26 UTC, l-ohman commented on frontend/common/types.ts
> +      lot.custom_lot_attributes.mmr = Math.floor(lot.custom_lot_attributes.mmr);
Recently I've had some MMRs in my DB as decimal numbers. I'm unsure if this is an issue with our `import_auction` process, the `playerdata_backfiller`, or even something else, but this seemed like the simplest fix until that gets resolved.

2023-08-12 00:39 UTC, l-ohman commented on frontend/common/types.ts
> +        timeNominated: lot.time_nominated ? new Date(lot.time_nominated) : null,
No, because calling `new Date(null)` returns a valid date (the UNIX Epoch). Since we use this `timeNominated` field to generate our auction's history, we need this to be a falsey value if a Lot has not yet been nominated.

2023-08-12 00:41 UTC, l-ohman commented on frontend/components/auction/BidderActions/BidderMenu.tsx
> +      );
https://www.youtube.com/watch?v=xyPll1e9FrA

2023-08-12 00:48 UTC, cadenforrest approved these changes

2023-08-12 00:49 UTC, merged