BidderNotes (favorites) vertical slice
cadenforrest/DotaLeagueSite pull request #166
Opened 2023-10-17 16:06 UTC by l-ohman

- BidderNote table in DB
- API routes to get/update BidderNotes
- Ability for bidders to favorite/unfavorite lots via the PlayerTable

Looking for feedback on my implementation of a unique constraint, as well as how I'm updating the data on the frontend (with the useSWR "mutate" fn).

![Table with new favorites column](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/c03b82a0-cb0f-4dd1-8205-39bf95320024)

2023-10-17 16:45 UTC, kmorrison requested changes

2023-10-17 16:45 UTC, kmorrison commented on api/backend/auction/views.py
> +            return Response(input_note.errors, status=status.HTTP_400_BAD_REQUEST)
i like the style where if the whole function is in an `if`, instead putting the negated if as an early return and writing the rest of the function on top level

so `if not valid(): return....` then you can unindent everything

2023-10-17 16:45 UTC, kmorrison commented on api/backend/auction/views.py
> +            if len(association)==1:
`len` evals the whole query into memory then checks the length of the list. probably what you want here is `association.count()` (which keeps all the counting on the db side) or `association.exists()` (where again on the db side it just checks if there's any row).

also, i see you're doing get or create?
```
association, created = models.BidderNote.objects.get_or_create(bidder_id=bidder.id, lot_id=lot.id)
association.favorite = favorite
association.save()
```

2023-10-17 16:45 UTC, kmorrison commented on api/backend/auction/views.py
> +                    nominate_order=nominate_order
boy what is you doin. put that trailing comma back

2023-10-17 16:45 UTC, kmorrison commented on api/backend/auction/views.py
> +                "favorite": favorite
add trailing comma

2023-10-17 18:28 UTC, l-ohman commented on api/backend/auction/views.py
> +            if len(association)==1:
Originally I had a `get_or_create`, but I ended up having 2 items in the DB for every bidder/lot pair with that method - one with 'favorite' as True, and the other with 'favorite' as 'False'. I also tried `create_or_update` but couldn't get that working properly either.

2023-10-17 19:30 UTC, kmorrison commented on api/backend/auction/views.py
> +            if len(association)==1:
So `get_or_create(a=a, b=b, c=c)` will upsert one unique entry for every unique triple of (a, b, c). So really what you want is `get_or_create(**keys_i_care_about)`, and then do work on the resulting object like making sure `favorite` is set correctly.

2023-10-17 19:59 UTC, cadenforrest commented on api/backend/auction/models.py
> +        return f"{self.bidder.name} favorited {self.lot.name} ({self.favorite})"
What's the use case for having a `BidderNote` with `favorite=False`? It seems like in that case, having no `BidderNote` row at all could mean the same thing.

2023-10-17 19:59 UTC, cadenforrest commented on api/backend/auction/views.py
> +            models.BidderNote.objects.create(bidder_id=bidder.id, lot_id=lot.id, favorite=favorite)
❓ Why do we need to do this? Shouldn't the model enforce uniqueness for us?

2023-10-17 20:01 UTC, cadenforrest commented on api/backend/auction/views.py
> +            models.BidderNote.objects.create(bidder_id=bidder.id, lot_id=lot.id, favorite=favorite)
Oh I see, this is like a `create_or_update` sorta thing?

2023-10-17 21:52 UTC, l-ohman commented on api/backend/auction/views.py
> +            models.BidderNote.objects.create(bidder_id=bidder.id, lot_id=lot.id, favorite=favorite)
Yes it's effectively a `create_or_update`. I'm not sure why the model didn't enforce the uniqueness as specified in `models.py`, but as mentioned before it was allowing 2 of the same bidder/lot pairs to coexist in the database (one with favorite as True, and the other as False).

2023-10-17 21:53 UTC, l-ohman commented on api/backend/auction/models.py
> +        return f"{self.bidder.name} favorited {self.lot.name} ({self.favorite})"
In our original plan, there was talk of using this table for other information as well (hence why I did not name the model `Favorite`). If someone were to unfavorite a Lot, that shouldn't affect any other information they may have stored on that Lot, such as written notes.

2023-10-18 18:02 UTC, kmorrison requested changes
getting there, have some testing requests

2023-10-18 18:02 UTC, kmorrison commented on api/backend/tests/auction/test_auction_api.py
> +    assert not data[1]
this parts a little unclear... does the get only return [True, False], because that would be crazy. I suspect you'd have to be more specific, like `assert data[0]['bidder'] == bidder; assert data[0]['favorite']... etc`

2023-10-18 18:29 UTC, l-ohman commented on api/backend/tests/auction/test_auction_api.py
> +    assert not data[1]
Yeah, that was a mistake. I've updated them to `data[0]["favorite"]`.

For reference, the response is an array of these objects:
```
{
    "id": 86,
    "lot": 1642,
    "bidder": 375,
    "favorite": false,
    "created": "2023-10-18T15:36:14.372183Z",
    "updated": "2023-10-18T15:36:17.810347Z"
}
```

2023-10-18 18:30 UTC, kmorrison commented on api/backend/tests/auction/test_auction_api.py
> +    response = authed_client.post("/api/biddernotes/", note)
I guess it's fine to infer "not set" as True. I meant more that we should never to inference, in order to set it to true you need to pass in `favorite=True`, and unset or favorite=None should 400. Thoughts?

2023-10-18 19:16 UTC, l-ohman commented on api/backend/tests/auction/test_auction_api.py
> +    response = authed_client.post("/api/biddernotes/", note)
Ah I see, yeah you're probably right. Currently it actually does 400 if the `favorite` is unset (which was not my intention) - but I'll update the behavior for favorite being anything other than a boolean.

2023-10-18 19:18 UTC, kmorrison approved these changes

2023-10-18 19:29 UTC, merged