Update DataGrid to support different auction types and tenants
cadenforrest/DotaLeagueSite pull request #190
Opened 2023-10-26 19:12 UTC by l-ohman

**Note:** The diff for this PR is very large, but once #186 gets approved and merged it should come down quite a bit.

This PR changes the way the DataGrid is implemented to simplify the process of adapting it to different auction types and tenants. There are changes to the PlayerTable, CaptainTable, and TeamTable (but none to the HistoryTab).

# Changes and notes

## PlayerTable

Restructured the columns so they are easier to change. (This can be taken a lot further in terms of configurability, but seems unnecessary at the moment). Currently, the columns are based on tenant instead of auction_type, because the PlayerTable should be the same regardless of auction type—this table only needs to change to support different signup information, which is specific to tenants.

## CaptainTable

Restructured the columns so they are easier to change. There is a bit of pseudocode here since I don't have the imported data yet, but it's not too far from completion. Here is a comparison of the Captain Auction (left) to the Supporter Auction (right):

![CaptainTable for both auction types](https://github.com/cadenforrest/DotaLeagueSite/assets/101072281/add9493d-0f60-4d11-b9d5-11c86186d307)

Once we have orgs, I'll add the captain's org name and logo as well. (Open to suggestions on what columns we want in this table, but those changes should probably be made in new PR.) 

## TeamTable

Lots of code changes, but nothing functional yet. Because the TeamTables are extremely different depending on the auction type, I decided to split them into 2 separate components entirely. This lays the groundwork for the new supporter auction TeamTable. (Originally I thought it would be straightforward to set this up without real data, but it seems way too tedious and time-consuming for now.) The current columns planned are:
- Org name and logo
- Total purse (captain + supporters purse)
- Number of supporters
- Players drafted (x/5)
- Average MMR of drafted players
- Roster full (boolean)

Open to suggestions on what columns we want in this table as well.

2023-10-26 22:50 UTC, cadenforrest requested changes

2023-10-26 22:50 UTC, cadenforrest commented on frontend/components/auction/DataGridSelection/PlayerTable/_PlayerTable.tsx
> +
This seems like a bit more of the same - 

```typescript
if (auctionState.type === "CAPTAIN" { 
    return playerTableColumnsRD2L;
} else if (auctionState.type === "CAPTAIN") { 
    return playerTableColumnsNADCL;
} else { ?????????? } 
```

Also... do we need to do this in a hook? You'd know best, but I'm curious to know why we need to do this hook. In both possible cases of dependency arrays, `[auction]` and `[subdomain]`, we don't really expect the thing we're checking here to ever change while the user is on the page (the auction isn't going to switch states while the user is on the page)

2023-10-26 22:54 UTC, cadenforrest commented on frontend/components/auction/DataGridSelection/_DataGridSelection.tsx
> +        {/* renders the correct tables based on subdomain  */}
🤔 is this true?

2023-10-26 22:55 UTC, cadenforrest commented on frontend/components/auction/DataGridSelection/TeamTable/_TeamTable.tsx
> +  // }
disabled because hydration error?

2023-10-27 14:02 UTC, l-ohman commented on frontend/components/auction/DataGridSelection/PlayerTable/_PlayerTable.tsx
> +
As mentioned in the original PR message, I believe this table should be based on tenant and not auction type:

> This table only needs to change to support different signup information, which is specific to tenants.

And for the useMemo -- I originally put it in a hook because I had some concern about performance, but I think I was just seeing ghosts. (And I'm pretty sure it's 0.001% slower with the hook anyway.) I'll remove it.

2023-10-27 14:03 UTC, l-ohman commented on frontend/components/auction/DataGridSelection/_DataGridSelection.tsx
> +        {/* renders the correct tables based on subdomain  */}
I have updated it from "subdomain" to "tenant or auction type".

2023-10-27 14:30 UTC, cadenforrest approved these changes

2023-10-27 14:31 UTC, merged